# Supergraph configuration for rover CLI
# Used to compose the supergraph schema from subgraphs

federation_version: =2.7.1

subgraphs:
  user-service:
    routing_url: http://user-service:8000/graphql
    schema:
      subgraph_url: http://user-service:8000/graphql
  
  robot-service:
    routing_url: http://robot-service:8001/graphql
    schema:
      subgraph_url: http://robot-service:8001/graphql
  
  site-service:
    routing_url: http://site-service:8002/graphql
    schema:
      subgraph_url: http://site-service:8002/graphql
