global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['rest-gateway:10000', 'strawberry-gateway:10000', 'apollo-router:10000']
    scrape_interval: 5s

  - job_name: 'robot-service'
    static_configs:
      - targets: ['robot-service:10001']

  - job_name: 'telemetry-service'
    static_configs:
      - targets: ['telemetry-service:10002']

  - job_name: 'alert-service'
    static_configs:
      - targets: ['alert-service:10003']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9417']
    scrape_interval: 5s
